### ISSUE TITLE
麻烦删一下隔壁你fork的那啥续期源码

### ISSUE THREAD

**Issue by spiritLHL** [hnauto/Autojs-bmob-sdk#1]
麻烦删一下隔壁你fork的那啥续期源码，不要开源，自用谢谢，你的上游被我劝删库了，我就是文中参考文章的作者，只求别捅破窗户纸。。。。上次coia的传开加了图片验证码，这次再来估计会加阴影模块啥随机元素了，只求不开源保平安。。。

**Comment by hnauto** [comment]
已取消fork,抱歉
